spring:
  profiles:
    active: local

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./data/testdb
      username: sa
      password:
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop